---
title: Exploratory Data Analysis
description:
toc: true
featuredVideo:
featuredImage: https://cdn.activestate.com/wp-content/uploads/2019/08/exploratory-data-analysis-using-python-blog-hero.jpg
draft: false
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>

<div id="TOC">

</div>

<p>Authors: Minghang Hong, Xianjue Huang, Xuan Wu, Yu Yan, and Yuchen Zhu</p>
<p><br></p>
<div id="what-do-we-care-about" class="section level2">
<h2>What do we care about?</h2>
<p>Suicide is a real problem worldwide: in the present time, approximately 130 Americans commit suicide every day, says the SAVE (n.d.). In addition, in Switzerland, people are even getting assisted in suicide actions and there might even be “Suicide pods that provide a ‘painless death’ soon (i24News 2021). Who knows if this will be a trend in the U.S. in the near future?</p>
<p>Suicide problems as a whole attract us, and we wondered if we can figure out the attributes as well as people’s different behaviors that may cause them to consider committing suicide. However, as we are all college students, we decided to look at suicide problems among people around our ages. Hence, comes our selection of the youth risk behavior dataset, which contains suicide consideration as a survey question with an age ranged from “younger than 12” to “older than 18”.</p>
<p>The dependent variable that we are interested in is, of course, serious_consideration_suicide, which takes binary value of yes or no to a question asking the surveyed about whether they have considered committing suicide seriously. Other variables that we are interested in are sex, and many other health risk behaviors that are introduced in the Data section of this project. The reason we are interested in those is that we wanted to find out what kind of health risk behaviors can contribute to consideration of suicide.</p>
<p>However, there are also some limitations of our analysis based on those variables. One of them is that the dataset mainly focused on individuals that are older than 11-year-old and younger than 19-year-old (12-18), we cannot use our model to predict adults’ or children’s possibility of considering suicide in the U.S. In addition, since the dataset takes answers from a survey based on multiple choices, we do not have many numerical values, and hence our model used many dummy variables.</p>
<p><br></p>
</div>
<div id="initial-data-analysis" class="section level2">
<h2>Initial Data Analysis</h2>
<p>During our initial phase of analysis, we were not sure what independent variables should be chosen so we first explored our data by plotting serious_consideration_suicide against age, sex, race, and weight status. Basically, we tried to see if physical status may already show strong trend with suicide considerations. To ease our work load, we first decided to only look at year 2019.</p>
<p><br></p>
<pre class="r"><code>library(tidyverse)
library(ggpubr)
library(modelr)
library(ROCR)
library(data.table)
library(formattable)</code></pre>
<pre class="r"><code>predict_suicide &lt;- data_2019 %&gt;% 
  select(race,age,sex,,Weight_status,serious_consideration_suicide) 
predict_suicide_model_inital &lt;- glm(serious_consideration_suicide ~ age + 
                                      race + sex+ Weight_status, 
                                    data = predict_suicide, family = binomial)
summary(predict_suicide_model_inital)</code></pre>
<pre><code>## 
## Call:
## glm(formula = serious_consideration_suicide ~ age + race + sex + 
##     Weight_status, family = binomial, data = predict_suicide)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -0.976  -0.693  -0.568  -0.497   2.147  
## 
## Coefficients:
##                                            Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)                                -0.99173    0.04934  -20.10  &lt; 2e-16
## age15                                       0.03489    0.02179    1.60     0.11
## age16                                       0.04504    0.02198    2.05     0.04
## age17                                       0.00901    0.02275    0.40     0.69
## age18+                                     -0.02402    0.02925   -0.82     0.41
## raceAsian                                  -0.47433    0.05674   -8.36  &lt; 2e-16
## raceBlack or African American              -0.50435    0.05005  -10.08  &lt; 2e-16
## raceHispanic/Latino                        -0.33421    0.04857   -6.88  6.0e-12
## raceMultiple Races (Non-Hispanic)           0.01495    0.05284    0.28     0.78
## raceNative Hawaiian/Other Pacific Islander -0.32307    0.07043   -4.59  4.5e-06
## raceWhite                                  -0.33366    0.04710   -7.08  1.4e-12
## sexMale                                    -0.68031    0.01429  -47.59  &lt; 2e-16
## Weight_statusobesity                        0.43676    0.01917   22.79  &lt; 2e-16
## Weight_statusoverweight                     0.22865    0.01882   12.15  &lt; 2e-16
## Weight_statusunderweight                    0.21770    0.04101    5.31  1.1e-07
##                                               
## (Intercept)                                ***
## age15                                         
## age16                                      *  
## age17                                         
## age18+                                        
## raceAsian                                  ***
## raceBlack or African American              ***
## raceHispanic/Latino                        ***
## raceMultiple Races (Non-Hispanic)             
## raceNative Hawaiian/Other Pacific Islander ***
## raceWhite                                  ***
## sexMale                                    ***
## Weight_statusobesity                       ***
## Weight_statusoverweight                    ***
## Weight_statusunderweight                   ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 136443  on 142913  degrees of freedom
## Residual deviance: 133348  on 142899  degrees of freedom
##   (39577 observations deleted due to missingness)
## AIC: 133378
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p><br>
The result of our preliminary exploration is surprising: we first thought that age would be a very important predictor, yet as the model above shows, none of the dummy variables for age was significant enough. However, we soon discovered that this could be explained by the graph below:</p>
<p><br></p>
<pre class="r"><code>data &lt;- data_2019 %&gt;% drop_na(serious_consideration_suicide, sex, race, Weight_status) 

a &lt;- data %&gt;% ggplot(aes(age)) + 
  geom_bar(aes(fill = as.character(serious_consideration_suicide)),
  position = &quot;fill&quot;) + labs(x = &#39;Age&#39;, y = &#39;Prop&#39;,fill = &quot;Suicide_Consideration&quot;) + coord_flip()
b &lt;- data %&gt;% ggplot(aes(age)) + 
  geom_bar(aes(fill = as.character(Weight_status)),
  position = &quot;fill&quot;) + labs(x = &#39;Age&#39;, y = &#39;Prop&#39;,fill = &quot;Weight_status&quot;) + coord_flip()
c &lt;- data %&gt;% ggplot(aes(age)) + 
  geom_bar(aes(fill = as.character(sex)),
  position = &quot;fill&quot;) + labs(x = &#39;Age&#39;, y = &#39;Prop&#39;,fill = &quot;sex&quot;) + coord_flip()

ggarrange(a, b, c, ncol = 2, nrow = 2)</code></pre>
<p><img src="/analysis_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre class="r"><code>data %&gt;% ggplot(aes(age)) + 
  geom_bar(aes(fill = as.character(race)),
  position = &quot;fill&quot;) + labs(x = &#39;Age&#39;, y = &#39;Prop&#39;,fill = &quot;race&quot;) + coord_flip()</code></pre>
<p><img src="/analysis_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<p><br></p>
<p>This is a graph that shows the proportion of people who have considered committing suicide across different age groups. The graph clearly shows that the distribution for the consideration and age seem to be universal. We also plotted age and other variables such as Weight_status and race, and the results were similar: there does not seem to have a significant effect between each dependent variable and age across different age groups. Hence age is permantly excluded from our dataset for model analysis purposes. We may still use it for graph generating and interactives.</p>
<p>Again, from the model before, we noticed that race seem to play an important role in prediction. Furthermore, we wanted to first make a model for minorities in the U.S. in order to see what variables actually affect their consideration for suicide. For this step, we used 4 races instead of using 7 races (combined together American Indian/Alaska Native, Asian, Native Hawaiian/Other Pacific Islander, and Multiple Races). This is to make sure the sample size is big enough, as shown below:</p>
<p><br></p>
<pre class="r"><code>processed_data %&gt;% count(race4) %&gt;% drop_na(race4) %&gt;% 
  mutate(perc = n / sum(n)) %&gt;% mutate(labels = scales::percent(perc)) %&gt;% 
  ggplot(aes(x=&quot;&quot;, y=n, fill= race4))+geom_bar(stat=&quot;identity&quot;, width=1) + 
  geom_text(aes(label = labels),
  position = position_stack(vjust = 0.5), size = 5, colour = &#39;white&#39;) +
  coord_polar(&quot;y&quot;, start=0) + theme_void() + labs(fill=&quot;Race&quot;)</code></pre>
<p><img src="/analysis_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p><br>
As shown on the graph, white population takes up almost 60% of the data, while Hispanic/Latino population takes up 15.4%, Black/African American population takes up almost 14%. Then all the other races combined just takes up 12.1% of the data. This trend is consistent with what has been shown on Wikipedia. Hence, we decided to continue by combining all other 4 races into a big minority race group.</p>
<p><br></p>
<pre class="r"><code>suicide_data_overview &lt;- processed_data %&gt;% 
  drop_na(c(serious_consideration_suicide,attempt_suicide,race4,plan_suicide)) %&gt;% 
  select(year, race4, serious_consideration_suicide,attempt_suicide,plan_suicide) %&gt;% 
  group_by(year,race4) %&gt;% summarise(prob_consider = sum(serious_consideration_suicide)/n(),
                                     prob_plan = sum(plan_suicide)/n(), prob_attempt = sum(attempt_suicide)/n())
a &lt;- ggplot(suicide_data_overview, aes(x = year))+ 
  geom_line(aes(y = prob_consider, color = race4)) +
  labs(title=&quot;Probability of suicide consideration, plan, and attempt&quot;,color = &quot;Race&quot;)
b &lt;- ggplot(suicide_data_overview, aes(x = year))+ 
  geom_line(aes(y = prob_plan,color = race4))+labs(color = &quot;Race&quot;)
c &lt;- ggplot(suicide_data_overview, aes(x = year))+ 
  geom_line(aes(y = prob_attempt,color = race4))+labs(color = &quot;Race&quot;)
ggarrange(a, b, c, ncol = 1, nrow = 3)</code></pre>
<p><img src="/analysis_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p><br></p>
<p>The graph above shows that all other Races (the red line) overall seem to have higher chance for suicide consideration, planning, and attempting. Hence, this shows that our interest of minority might be a good one to look at.</p>
<p><br></p>
</div>
<div id="modeling" class="section level2">
<h2>Modeling</h2>
<p><br></p>
<pre class="r"><code>minority &lt;- processed_data %&gt;% filter(race4 == &quot;All Other Races&quot;)
head(minority,5)</code></pre>
<pre><code>## # A tibble: 5 × 37
##   sitename  year age   sex   grade race4 race  height_without_… weight_without_…
##   &lt;chr&gt;    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;            &lt;dbl&gt;            &lt;dbl&gt;
## 1 Florida…  2007 16    Male  10th… All … Mult…             1.78             74.8
## 2 Florida…  2007 16    Male  10th… All … Asian             1.7              66.2
## 3 Florida…  2007 16    Male  9th … All … Asian             1.57             63.5
## 4 Florida…  2007 16    Male  9th … All … Amer…             1.75             54.4
## 5 Florida…  2007 16    Male  10th… All … Asian             1.75             95.3
## # … with 28 more variables: bmi &lt;dbl&gt;, bmi_percentage &lt;dbl&gt;,
## #   seat_belt_use &lt;chr&gt;, riding_with_a_drinking_driver &lt;chr&gt;,
## #   weapon_carrying &lt;chr&gt;, weapon_carrying_at_school &lt;chr&gt;,
## #   safety_concerns_at_school &lt;chr&gt;, Threatened_at_school &lt;chr&gt;,
## #   Physical_fighting &lt;chr&gt;, Physical_fighting_at_school &lt;chr&gt;,
## #   feel_hopeless_2+weeks &lt;chr&gt;, serious_consideration_suicide &lt;dbl&gt;,
## #   plan_suicide &lt;dbl&gt;, attempt_suicide &lt;dbl&gt;, freq_smoking_cigarette &lt;chr&gt;, …</code></pre>
<p><br></p>
<p>This step is to create the sub-dataset for minority population for exploration.</p>
<p><br></p>
<pre class="r"><code>#create a dataframe record cross-validation results
df &lt;- data.frame(matrix(ncol=5,nrow=0, dimnames=list(NULL, c(&quot;Model&quot;,&quot;Train_Test_split&quot;,&quot;TrainingSet&quot;, &quot;TestingSet&quot;, &quot;AUC&quot;))))</code></pre>
<pre class="r"><code>df %&gt;% mutate(AUC = as.numeric(AUC)) %&gt;% 
  mutate_if(is.numeric, round, digits = 3) %&gt;% 
  formattable(list(`AUC`= color_tile(&quot;#DeF7E9&quot;,&quot;#71CA97&quot;)))</code></pre>
<table class="table table-condensed">
<thead>
<tr>
<th style="text-align:right;">
Model
</th>
<th style="text-align:right;">
Train_Test_split
</th>
<th style="text-align:right;">
TrainingSet
</th>
<th style="text-align:right;">
TestingSet
</th>
<th style="text-align:right;">
AUC
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
Minority
</td>
<td style="text-align:right;">
50/50
</td>
<td style="text-align:right;">
1:12890
</td>
<td style="text-align:right;">
12891:25780
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #79cd9d">0.727</span>
</td>
</tr>
<tr>
<td style="text-align:right;">
Minority
</td>
<td style="text-align:right;">
50/50
</td>
<td style="text-align:right;">
12891:25780
</td>
<td style="text-align:right;">
1:12890
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #b4e5c9">0.720</span>
</td>
</tr>
<tr>
<td style="text-align:right;">
Minority
</td>
<td style="text-align:right;">
67/33
</td>
<td style="text-align:right;">
1:17187
</td>
<td style="text-align:right;">
17188:25780
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #71ca97">0.728</span>
</td>
</tr>
<tr>
<td style="text-align:right;">
Minority
</td>
<td style="text-align:right;">
67/33
</td>
<td style="text-align:right;">
1:8593 &amp; 17188:25780
</td>
<td style="text-align:right;">
8594:17187
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #71ca97">0.728</span>
</td>
</tr>
<tr>
<td style="text-align:right;">
Minority
</td>
<td style="text-align:right;">
67/33
</td>
<td style="text-align:right;">
8594:25780
</td>
<td style="text-align:right;">
1:8593
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #def7e9">0.715</span>
</td>
</tr>
<tr>
<td style="text-align:right;">
All_Race
</td>
<td style="text-align:right;">
50/50
</td>
<td style="text-align:right;">
1:137263
</td>
<td style="text-align:right;">
137264:274527
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #bce9cf">0.719</span>
</td>
</tr>
<tr>
<td style="text-align:right;">
All_Race
</td>
<td style="text-align:right;">
50/50
</td>
<td style="text-align:right;">
137264:274527
</td>
<td style="text-align:right;">
1:137263
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #bce9cf">0.719</span>
</td>
</tr>
<tr>
<td style="text-align:right;">
All_Race
</td>
<td style="text-align:right;">
67/33
</td>
<td style="text-align:right;">
1:91509
</td>
<td style="text-align:right;">
91510:274527
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #bce9cf">0.719</span>
</td>
</tr>
<tr>
<td style="text-align:right;">
All_Race
</td>
<td style="text-align:right;">
67/33
</td>
<td style="text-align:right;">
1:91509 &amp; 183019:274527
</td>
<td style="text-align:right;">
91510:183018
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #a3debc">0.722</span>
</td>
</tr>
<tr>
<td style="text-align:right;">
All_Race
</td>
<td style="text-align:right;">
67/33
</td>
<td style="text-align:right;">
91510:274527
</td>
<td style="text-align:right;">
1:91509
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #c4ecd6">0.718</span>
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>attach(mtcars)
par(mfrow=c(1,2))

prob &lt;- predict(train_model_new, newdata = minor_Test, type = &quot;response&quot;)
pred &lt;- prediction(prob, minor_Test$serious_consideration_suicide) 
perf &lt;- performance(pred, measure = &quot;tpr&quot;, x.measure = &quot;fpr&quot;)
plot(perf, main=&quot;ROC curve for Minority Model&quot;)

prob &lt;- predict(train_model_new, newdata = whole_Test, type = &quot;response&quot;)
pred &lt;- prediction(prob, whole_Test$serious_consideration_suicide) 
perf &lt;- performance(pred, measure = &quot;tpr&quot;, x.measure = &quot;fpr&quot;)
plot(perf, main=&quot;ROC curve for All_Race Model&quot;)</code></pre>
<p><img src="/analysis_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p><br></p>
<p>Based on our forward model selection, we have obtained our models and AUC values. Based on the AUC values we got from cross validations (full steps are posted after Bibliography section), we choose the third model from Minority dataset and the fourth model from All_Race dataset.</p>
<p><br></p>
<p>For the Minority dataset, the model has an AUC value of 0.728, and the model is: serious_consideration_suicide ~ sex + weapon_carrying + safety_concerns_at_school + Threatened_at_school + first_time_drinking + total_num_get_high + has_got_drug_at_school</p>
<p><br></p>
<pre class="r"><code># Minority Model
minor_Train &lt;- minor[1:17187,]
minor_Test &lt;- minor[17188:25780,]

attach(minor_Train)

leaps_f &lt;- leaps::regsubsets(serious_consideration_suicide ~ sex + 
                               Weight_status + 
                               weapon_carrying + weapon_carrying_at_school + 
                               safety_concerns_at_school + 
                               Threatened_at_school + 
                               total_num_methamphetamines + 
                               first_time_drinking + 
                               num_cigarette_per_day + 
                               total_num_get_high + 
                               total_num_needle_for_drug + 
                               has_got_drug_at_school, 
                             method = &quot;forward&quot;, data = minor_Train, nvmax =10)

Final_minor_model &lt;- glm(serious_consideration_suicide ~ sex + weapon_carrying + 
                           safety_concerns_at_school + Threatened_at_school + 
                           first_time_drinking + total_num_get_high + 
                           has_got_drug_at_school, family = binomial)

summary(Final_minor_model)</code></pre>
<pre><code>## 
## Call:
## glm(formula = serious_consideration_suicide ~ sex + weapon_carrying + 
##     safety_concerns_at_school + Threatened_at_school + first_time_drinking + 
##     total_num_get_high + has_got_drug_at_school, family = binomial)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -2.060  -0.658  -0.516  -0.334   2.414  
## 
## Coefficients:
##                              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                   -1.1670     0.0497  -23.50  &lt; 2e-16 ***
## sexMale                       -0.9066     0.0453  -20.00  &lt; 2e-16 ***
## weapon_carryingYes             0.4667     0.0551    8.47  &lt; 2e-16 ***
## safety_concerns_at_schoolYes   0.6733     0.0782    8.61  &lt; 2e-16 ***
## Threatened_at_schoolYes        0.7386     0.0708   10.43  &lt; 2e-16 ***
## first_time_drinking13+        -0.2541     0.0502   -5.06  4.2e-07 ***
## first_time_drinkingHaven&#39;t    -0.7837     0.0586  -13.37  &lt; 2e-16 ***
## total_num_get_highYes          0.7690     0.0564   13.64  &lt; 2e-16 ***
## has_got_drug_at_schoolYes      0.5128     0.0453   11.33  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 16856  on 17186  degrees of freedom
## Residual deviance: 15047  on 17178  degrees of freedom
## AIC: 15065
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<pre class="r"><code>detach(minor_Train)</code></pre>
<p><br></p>
<p>For the All_Race dataset, the model has an AUC value of 0.722, and the model is:
serious_consideration_suicide ~ sex + weapon_carrying + safety_concerns_at_school + Threatened_at_school + total_num_methamphetamines + first_time_drinking + total_num_get_high + has_got_drug_at_school</p>
<p><br></p>
<pre class="r"><code># All_Race Model
whole1 &lt;- whole[1:91509,]
whole2 &lt;- whole[91510:183018,]
whole3 &lt;- whole[183019:274527,]

whole_Train &lt;- rbind(whole1,whole3)
whole_Test &lt;- whole2

attach(whole_Train)

leaps_f &lt;- leaps::regsubsets(serious_consideration_suicide ~ sex + 
                               Weight_status + weapon_carrying + 
                               weapon_carrying_at_school + 
                               safety_concerns_at_school + 
                               Threatened_at_school + 
                               total_num_methamphetamines + 
                               first_time_drinking + 
                               num_cigarette_per_day + 
                               total_num_get_high + 
                               total_num_needle_for_drug + 
                               has_got_drug_at_school, 
                             method = &quot;forward&quot;, data = whole_Train, nvmax =10)

Final_whole_model &lt;- glm(serious_consideration_suicide ~ sex + 
                           weapon_carrying + 
                           safety_concerns_at_school + 
                           Threatened_at_school +
                           total_num_methamphetamines + 
                           first_time_drinking + 
                           total_num_get_high + 
                           has_got_drug_at_school, family = binomial)

summary(Final_whole_model)</code></pre>
<pre><code>## 
## Call:
## glm(formula = serious_consideration_suicide ~ sex + weapon_carrying + 
##     safety_concerns_at_school + Threatened_at_school + total_num_methamphetamines + 
##     first_time_drinking + total_num_get_high + has_got_drug_at_school, 
##     family = binomial)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -2.180  -0.578  -0.461  -0.300   2.500  
## 
## Coefficients:
##                               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                    -1.4159     0.0163   -86.9   &lt;2e-16 ***
## sexMale                        -0.8914     0.0153   -58.4   &lt;2e-16 ***
## weapon_carryingYes              0.4215     0.0185    22.8   &lt;2e-16 ***
## safety_concerns_at_schoolYes    0.7228     0.0262    27.6   &lt;2e-16 ***
## Threatened_at_schoolYes         0.7752     0.0239    32.4   &lt;2e-16 ***
## total_num_methamphetaminesYes   0.5142     0.0279    18.4   &lt;2e-16 ***
## first_time_drinking13+         -0.2883     0.0164   -17.6   &lt;2e-16 ***
## first_time_drinkingHaven&#39;t     -0.7739     0.0201   -38.5   &lt;2e-16 ***
## total_num_get_highYes           0.7769     0.0190    41.0   &lt;2e-16 ***
## has_got_drug_at_schoolYes       0.4834     0.0152    31.9   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 160557  on 183017  degrees of freedom
## Residual deviance: 143984  on 183008  degrees of freedom
## AIC: 144004
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<pre class="r"><code>detach(whole_Train)</code></pre>
<p><br></p>
<p>Based on the result from forward selection and cross-validation, All_Race model has one more variable than Minority model. The variable, though named as total_num_methamphetamines, is a categorical variable that indicates whether the individual ever had used methamphetamines - if he/she had used even once, we considered he/she had used it.</p>
<p><br></p>
<pre class="r"><code># Minority Model
Final_model_coef &lt;- coef(Final_minor_model)
Predict_Probs &lt;- matrix(1:8, nrow = 8, 
                    dimnames = list(c(&quot;If a teenager is Male&quot;,
                  &quot;If a teenager carrying weapon during past days&quot;,
                  &quot;If a teenager feel unsafe at School&quot;, 
                  &quot;If a teenager are threatened by weapons on campus&quot;, 
                  &quot;If a teenager drank after age 13 for the first time&quot;, 
                  &quot;If a teenager have never drink alcohol yet&quot;,
                  &quot;If a teenager got high by taking drugs&quot;,
                  &quot;If a teenager had got drugs / got drug offerings at school&quot;), c(&quot;Probability_considering_suicide_change_by_in_percentage&quot;)))
for (i in 1:8) {
    Predict_Probs[i] &lt;- ((exp(Final_model_coef[i+1]) / 
                            (1+exp(Final_model_coef[i+1])) - 
                            exp(0)/(1+exp(0)))*100)
    i &lt;- i+1
}

#All_race model
Final_whole_model_coef &lt;- coef(Final_whole_model)
Predict_Probs_whole &lt;- matrix(2:9, nrow = 9, 
                    dimnames = list(c(&quot;If a teenager is Male&quot;,
                  &quot;If a teenager carrying weapon during past days&quot;,
                  &quot;If a teenager feel unsafe at School&quot;, 
                  &quot;If a teenager are threatened by weapons on campus&quot;,
                  &quot;If a teenager tried methamphetamines&quot;,
                  &quot;If a teenager drank after age 13 for the first time&quot;, 
                  &quot;If a teenager have never drink alcohol yet&quot;,
                  &quot;If a teenager got high by taking drugs&quot;,
                  &quot;If a teenager had got drugs / got drug offerings at school&quot;), c(&quot;Probability_considering_suicide_change_by_in_percentage&quot;)))</code></pre>
<pre><code>## Warning in matrix(2:9, nrow = 9, dimnames = list(c(&quot;If a teenager is Male&quot;, :
## data length [8] is not a sub-multiple or multiple of the number of rows [9]</code></pre>
<pre class="r"><code>for (i in 1:9) {
    Predict_Probs_whole[i] &lt;- ((exp(Final_whole_model_coef[i+1]) / 
                                  (1+exp(Final_whole_model_coef[i+1])) - 
                                  exp(0)/(1+exp(0)))*100)
    i &lt;- i+1
}

#build dataframe for both model and connect them together
merged_table &lt;- merge(as.data.frame.matrix(Predict_Probs),
                      as.data.frame.matrix(Predict_Probs_whole),
                      by = &quot;row.names&quot;, all = TRUE)%&gt;%  arrange(desc(Probability_considering_suicide_change_by_in_percentage.y)) %&gt;% 
mutate(difference = Probability_considering_suicide_change_by_in_percentage.x - Probability_considering_suicide_change_by_in_percentage.y)

colnames(merged_table) &lt;- c(&#39;Health Risk Behaviors&#39;,
                            &#39;Minority&#39;,
                            &#39;All_Race&#39;,
                            &#39;Difference&#39;)

round_df &lt;- function(df, digits) {
  nums &lt;- vapply(df, is.numeric, FUN.VALUE = logical(1))

  df[,nums] &lt;- round(df[,nums], digits = digits)

  (df)
}

merged_table &lt;- round_df(merged_table, digits=3)

merged_table$Minority[is.na(merged_table$Minority)]&lt;-&quot;N/A&quot;
merged_table$Difference[is.na(merged_table$Difference)]&lt;-0

merged_table %&gt;% formattable(list( Minority = color_tile(&quot;#D4FEC6&quot;,&quot;#FEC6C6&quot;),
                            All_Race = color_tile(&quot;#D4FEC6&quot;,&quot;#FEC6C6&quot;), 
                            Difference = formatter(&quot;span&quot;,
                              style = ~ style(color = ifelse(`Difference` &gt; 0, 
                          &quot;green&quot;, ifelse(`Difference` == 0, &quot;black&quot;, &quot;red&quot;))),~
                           icontext(sapply(`Difference`, function(x) if (x &lt; 0) 
                             &quot;arrow-down&quot; else if (x&gt; 0) &quot;arrow-up&quot; 
                             else if (x == 0) &quot;&quot; else &quot;&quot;), `Difference`))))</code></pre>
<pre><code>## Warning in gradient(as.numeric(x), ...): NAs introduced by coercion</code></pre>
<table class="table table-condensed">
<thead>
<tr>
<th style="text-align:right;">
Health Risk Behaviors
</th>
<th style="text-align:right;">
Minority
</th>
<th style="text-align:right;">
All_Race
</th>
<th style="text-align:right;">
Difference
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
If a teenager got high by taking drugs
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #fec6c6">18.331 </span>
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #fec6c6">18.50</span>
</td>
<td style="text-align:right;">
<span style="color: red">
<i class="glyphicon glyphicon-arrow-down"></i>
-0.172
</span>
</td>
</tr>
<tr>
<td style="text-align:right;">
If a teenager are threatened by weapons on campus
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #fdc6c6">17.669 </span>
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #fdc6c6">18.46</span>
</td>
<td style="text-align:right;">
<span style="color: red">
<i class="glyphicon glyphicon-arrow-down"></i>
-0.795
</span>
</td>
</tr>
<tr>
<td style="text-align:right;">
If a teenager feel unsafe at School
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #fbc8c6">16.224 </span>
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #fcc7c6">17.32</span>
</td>
<td style="text-align:right;">
<span style="color: red">
<i class="glyphicon glyphicon-arrow-down"></i>
-1.098
</span>
</td>
</tr>
<tr>
<td style="text-align:right;">
If a teenager tried methamphetamines
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px">N/A </span>
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #f7cec6">12.58</span>
</td>
<td style="text-align:right;">
<span style="color: black">
<i class="glyphicon glyphicon-"></i>
0
</span>
</td>
</tr>
<tr>
<td style="text-align:right;">
If a teenager had got drugs / got drug offerings at school
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #f7cec6">12.546 </span>
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #f6cfc6">11.85</span>
</td>
<td style="text-align:right;">
<span style="color: green">
<i class="glyphicon glyphicon-arrow-up"></i>
0.692
</span>
</td>
</tr>
<tr>
<td style="text-align:right;">
If a teenager carrying weapon during past days
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #f6cfc6">11.459 </span>
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #f5d1c6">10.38</span>
</td>
<td style="text-align:right;">
<span style="color: green">
<i class="glyphicon glyphicon-arrow-up"></i>
1.075
</span>
</td>
</tr>
<tr>
<td style="text-align:right;">
If a teenager drank after age 13 for the first time
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #e3e8c6">-6.319 </span>
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #e2eac6">-7.16</span>
</td>
<td style="text-align:right;">
<span style="color: green">
<i class="glyphicon glyphicon-arrow-up"></i>
0.838
</span>
</td>
</tr>
<tr>
<td style="text-align:right;">
If a teenager have never drink alcohol yet
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #d6fac6">-18.647</span>
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #d6fac6">-18.44</span>
</td>
<td style="text-align:right;">
<span style="color: red">
<i class="glyphicon glyphicon-arrow-down"></i>
-0.21
</span>
</td>
</tr>
<tr>
<td style="text-align:right;">
If a teenager is Male
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #d4fec6">-21.23 </span>
</td>
<td style="text-align:right;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #d4fec6">-20.92</span>
</td>
<td style="text-align:right;">
<span style="color: red">
<i class="glyphicon glyphicon-arrow-down"></i>
-0.312
</span>
</td>
</tr>
</tbody>
</table>
<div id="above-table-change-in-probability-of-suicide-consideration-due-to-various-health-risk-behaviors" class="section level3">
<h3>Above Table: Change in probability of suicide consideration due to various health risk behaviors</h3>
<p><br></p>
<p>Interestingly, according to the above chart, whether the young individual is a male or female plays an important role in predicting whether he/she might have serious consideration for suicide. Holding all other variables as default, being a male is 20 percent less likely to declare that he had serious consideration to suicide. In addition, another interesting fact is that never drink alcohol and drink alcohol after age 13 can be useful for helping to decrease the possibility for suicide consideration. In other words, teenagers who start to drink alcohol after age 13 have a higher rate of suicide consideration. For the leading factors that cause youth suicide, we find that ‘taking drugs and got high’, ‘being threatened by weapons on campus’, and ‘feeling unsafe at school’ are three main contributors to increase the possibility of considering suicide. This makes sense as all of these may bring tremendous stress to students on campus and may drive them to consider suicide, if they cannot restore their mental health on time. Furthermore, as the factor methamphetamine is not shown in the minority model, this indicates that methamphetamine usage is more correlated with suicide consideration for races such as White, Black and Latino rather than Minority.</p>
<p><br></p>
<p>As we just mentioned above that if a teenager is male, then this person’s predicted probability of considering suicide decreases by 20 percent. This finding motivates us to delve deeper. We are interested in this difference and decide to see whether the real suicide correlates with the results of the model. To do so, we combined the NCHS dataset (previously mentioned in the data section), which consists of real suicide death data, with our original dataset. We clean and merged two datasets to calculate the ratio between suicide death and suicide consideration from 1999 to 2019.</p>
<p><br>
To do so, our first step is to create a table for false positive rate and true positive rate in ROC curve.</p>
<pre class="r"><code># draw table for threshold, fpr, and tpr for finding the optimal threshold
prob &lt;- predict(Final_minor_model, newdata = minor_Test, type = &quot;response&quot;)
pred &lt;- prediction(prob, minor_Test$serious_consideration_suicide) 
perf &lt;- performance(pred, measure = &quot;tpr&quot;, x.measure = &quot;fpr&quot;)
cutoffs &lt;- data.frame(threshold=perf@alpha.values[[1]], fpr=perf@x.values[[1]], 
                      tpr=perf@y.values[[1]])
head(cutoffs,5)</code></pre>
<pre><code>##   threshold      fpr     tpr
## 1       Inf 0.000000 0.00000
## 2     0.880 0.000000 0.00546
## 3     0.822 0.000288 0.00728
## 4     0.815 0.000288 0.00850
## 5     0.789 0.001152 0.01335</code></pre>
<p><br>
Then, We used Geometric_Mean method to find the optimal threshold for classification.</p>
<pre class="r"><code>cutoffs &lt;- cutoffs %&gt;%  mutate(Geometric_Mean = sqrt(tpr * (1-fpr))) %&gt;% 
  arrange(desc(Geometric_Mean)) 
Optimal_threshold = cutoffs$threshold[1]</code></pre>
<p><br>
Then, we used the optimal threshold to classify the suicide consideration using the probability we get from our ALL_Race model.</p>
<pre class="r"><code>classified_minor &lt;- processed_data %&gt;% filter(race4 == &quot;All Other Races&quot;) %&gt;% drop_na(c(year,sitename,sex,serious_consideration_suicide,sex,weapon_carrying, 
          safety_concerns_at_school,Threatened_at_school,first_time_drinking,
          total_num_get_high,has_got_drug_at_school)) %&gt;%
  modelr::add_predictions(train_model_new) %&gt;% 
  mutate(prob_suicide_cont = exp(pred)/(1+exp(pred))) %&gt;% 
  mutate(classified_suicide_cont = ifelse(
    prob_suicide_cont &gt;= Optimal_threshold,1, 0)) %&gt;% select(!c(pred,grade,seat_belt_use,riding_with_a_drinking_driver,
          weapon_carrying_at_school,Physical_fighting,
          Physical_fighting_at_school,&#39;feel_hopeless_2+weeks&#39;,
          freq_smoking_cigarette,num_cigarette_per_day,freq_smoking_cigar,
          freq_drinking,total_num_marijuana,first_time_marijuana,
          total_num_cocaine,total_num_heroin,total_num_methamphetamines,
          total_num_needle_for_drug,Weight_status)) </code></pre>
<p><br>
Now, let’s combine and merge two dataset and also draw the ratio chart.</p>
<pre class="r"><code>real_suicide &lt;- fread(&quot;suicide.txt&quot;)

processed_suicide &lt;- real_suicide %&gt;% select(Year, Race, Gender,
                                `Single-Year Ages Code`,Deaths,Population) %&gt;% 
  filter(`Single-Year Ages Code` &lt;= 19 &amp; `Single-Year Ages Code` &gt;= 11) 

# fill na with 0 for further calculation
processed_suicide$Population = 
  as.numeric(as.character(processed_suicide$Population))</code></pre>
<pre><code>## Warning: NAs introduced by coercion</code></pre>
<pre class="r"><code>processed_suicide[is.na(processed_suicide)] &lt;- 0

# Create a table for real suicide occurrence for gender in each year
suicide_gender_A &lt;- processed_suicide %&gt;% group_by(Year,Gender) %&gt;% 
  summarise(Deaths = sum(Deaths))</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;Year&#39;. You can override using the `.groups` argument.</code></pre>
<pre class="r"><code>suicide_gender_B &lt;- processed_suicide %&gt;% group_by(Year,Gender) %&gt;% 
  summarise(Population = sum(Population))</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;Year&#39;. You can override using the `.groups` argument.</code></pre>
<pre class="r"><code>suicide_gender &lt;- left_join(suicide_gender_A, suicide_gender_B, 
                            by = c(&quot;Year&quot;,&quot;Gender&quot;)) %&gt;% 
  mutate(prob_real_suicide = Deaths/Population * 100) %&gt;% 
  select(Year, Gender, prob_real_suicide)

#rename columns name
names(suicide_gender)[names(suicide_gender) == &#39;Year&#39;] &lt;- &quot;year&quot;
names(suicide_gender)[names(suicide_gender) == &#39;Gender&#39;] &lt;- &quot;sex&quot;

predicted_suicide &lt;- classified_minor %&gt;% group_by(year,sex) %&gt;% 
  summarise(prob_suicide_cont = sum(classified_suicide_cont)/n())</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;year&#39;. You can override using the `.groups` argument.</code></pre>
<pre class="r"><code>suicide_comparsion_sex &lt;- left_join(suicide_gender,predicted_suicide, 
                                    by = c(&quot;year&quot;,&quot;sex&quot;)) %&gt;% 
  drop_na(prob_suicide_cont) %&gt;%
  mutate(ratio_real_to_cont = prob_real_suicide/prob_suicide_cont)
ggplot(suicide_comparsion_sex, 
       aes(x = year, y = ratio_real_to_cont,color = sex)) + 
       geom_line() + labs(y = &quot;Real / Consideration suicide Ratio&quot;)</code></pre>
<p><img src="/analysis_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p><br></p>
<p>Surprisingly, based on the above chart, we find that male has a significantly higher ratio compare to female. In other words, if a male and female declare they both have suicidal thoughts, then the male will be more likely to attempt suicide and cause death. This makes sense as female is more inclined to share their real thoughts and easier to get emotional, while the male is not very willing to tell their suicidal thoughts if they already decided to attempt the suicide.</p>
<p><br></p>
</div>
</div>
<div id="bibliography" class="section level2">
<h2>Bibliography</h2>
<p>i24News, Switzerland: Suicide pods provide a ‘painless death’, Dec 15, 2021., <a href="https://www.i24news.tv/en/news/international/europe/1639565590-switzerland-suicide-pods-being-developed-for-a-painless-death" class="uri">https://www.i24news.tv/en/news/international/europe/1639565590-switzerland-suicide-pods-being-developed-for-a-painless-death</a>)</p>
<p><br></p>
<p>Image from: <a href="https://cdn.activestate.com/wp-content/uploads/2019/08/exploratory-data-analysis-using-python-blog-hero.jpg" class="uri">https://cdn.activestate.com/wp-content/uploads/2019/08/exploratory-data-analysis-using-python-blog-hero.jpg</a></p>
<p><br></p>
<p>SAVE: Suicide Prevention, Information, and Awareness, n.d., (<a href="https://save.org/about-suicide/suicide-facts/" class="uri">https://save.org/about-suicide/suicide-facts/</a>)</p>
<p><br></p>
<p>Wikipedia, Race and ethnicity in the United States, <a href="https://en.wikipedia.org/wiki/Race_and_ethnicity_in_the_United_States" class="uri">https://en.wikipedia.org/wiki/Race_and_ethnicity_in_the_United_States</a></p>
</div>
